load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

java_proto_library(
    name = "exchange_o_gram",
    protos = ["exchange_o_gram.proto"],
    with_grpc = True,
    visibility = ['//visibility:public'],
)
