// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange_o_gram.proto
// Original file comments:
// Protobuf definition for Exchange-O-Gram
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace ExchangeOGram {
  public static partial class WallService
  {
    static readonly string __ServiceName = "exchange_o_gram.WallService";

    static readonly Marshaller<global::ExchangeOGram.PostToWallRequest> __Marshaller_PostToWallRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ExchangeOGram.PostToWallRequest.Parser.ParseFrom);
    static readonly Marshaller<global::ExchangeOGram.PostToWallResponse> __Marshaller_PostToWallResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ExchangeOGram.PostToWallResponse.Parser.ParseFrom);
    static readonly Marshaller<global::ExchangeOGram.GetWallPostsRequest> __Marshaller_GetWallPostsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ExchangeOGram.GetWallPostsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::ExchangeOGram.GetWallPostsResponse> __Marshaller_GetWallPostsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ExchangeOGram.GetWallPostsResponse.Parser.ParseFrom);

    static readonly Method<global::ExchangeOGram.PostToWallRequest, global::ExchangeOGram.PostToWallResponse> __Method_PostToWall = new Method<global::ExchangeOGram.PostToWallRequest, global::ExchangeOGram.PostToWallResponse>(
        MethodType.Unary,
        __ServiceName,
        "PostToWall",
        __Marshaller_PostToWallRequest,
        __Marshaller_PostToWallResponse);

    static readonly Method<global::ExchangeOGram.GetWallPostsRequest, global::ExchangeOGram.GetWallPostsResponse> __Method_GetWallPosts = new Method<global::ExchangeOGram.GetWallPostsRequest, global::ExchangeOGram.GetWallPostsResponse>(
        MethodType.ServerStreaming,
        __ServiceName,
        "GetWallPosts",
        __Marshaller_GetWallPostsRequest,
        __Marshaller_GetWallPostsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ExchangeOGram.ExchangeOGramReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WallService</summary>
    public abstract partial class WallServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ExchangeOGram.PostToWallResponse> PostToWall(global::ExchangeOGram.PostToWallRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetWallPosts(global::ExchangeOGram.GetWallPostsRequest request, IServerStreamWriter<global::ExchangeOGram.GetWallPostsResponse> responseStream, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WallService</summary>
    public partial class WallServiceClient : ClientBase<WallServiceClient>
    {
      /// <summary>Creates a new client for WallService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WallServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WallService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WallServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WallServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WallServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ExchangeOGram.PostToWallResponse PostToWall(global::ExchangeOGram.PostToWallRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PostToWall(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ExchangeOGram.PostToWallResponse PostToWall(global::ExchangeOGram.PostToWallRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PostToWall, null, options, request);
      }
      public virtual AsyncUnaryCall<global::ExchangeOGram.PostToWallResponse> PostToWallAsync(global::ExchangeOGram.PostToWallRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PostToWallAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::ExchangeOGram.PostToWallResponse> PostToWallAsync(global::ExchangeOGram.PostToWallRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PostToWall, null, options, request);
      }
      public virtual AsyncServerStreamingCall<global::ExchangeOGram.GetWallPostsResponse> GetWallPosts(global::ExchangeOGram.GetWallPostsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetWallPosts(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncServerStreamingCall<global::ExchangeOGram.GetWallPostsResponse> GetWallPosts(global::ExchangeOGram.GetWallPostsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetWallPosts, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WallServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WallServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static ServerServiceDefinition BindService(WallServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PostToWall, serviceImpl.PostToWall)
          .AddMethod(__Method_GetWallPosts, serviceImpl.GetWallPosts).Build();
    }

  }
}
#endregion
